-- Run once in the Supabase SQL editor. Private tables have no browser policies.
create table if not exists public.tapauth_students (
  id bigint generated by default as identity primary key, bucket_id text not null, device_id text not null,
  local_id bigint not null, student_no text not null, lastname text, firstname text,
  middlename text, fullname text, course text, project_type text, room text,
  created_at timestamptz, synced_at timestamptz not null default now(),
  unique(bucket_id, device_id, local_id)
);
create table if not exists public.tapauth_attendance (
  id bigint generated by default as identity primary key, bucket_id text not null, device_id text not null,
  local_id bigint not null, student_no text, status text, event_type text,
  date_logged timestamptz, time_entered timestamptz, time_left timestamptz,
  duration_seconds integer, duration_label text, synced_at timestamptz not null default now(),
  unique(bucket_id, device_id, local_id)
);
create table if not exists public.tapauth_reservations (
  id bigint generated by default as identity primary key, bucket_id text not null, device_id text not null,
  local_id bigint not null, service text not null, fullname text, student_no text,
  course text, reservation_date date, schedule_time time, duration_minutes integer,
  queue_position integer, teacher_name text, project_name text, purpose text,
  notes text, model_file_name text, status text, created_at timestamptz,
  updated_at timestamptz, synced_at timestamptz not null default now(),
  unique(bucket_id, device_id, local_id)
);
create table if not exists public.tapauth_public_activity (
  id bigint generated by default as identity primary key, bucket_id text not null, device_id text not null,
  local_id bigint not null, status text, event_type text, date_logged timestamptz,
  time_entered timestamptz, time_left timestamptz, duration_seconds integer,
  duration_label text, synced_at timestamptz not null default now(),
  unique(bucket_id, device_id, local_id)
);
alter table public.tapauth_students enable row level security;
alter table public.tapauth_attendance enable row level security;
alter table public.tapauth_reservations enable row level security;
alter table public.tapauth_public_activity enable row level security;
revoke all on public.tapauth_students from anon, authenticated;
revoke all on public.tapauth_attendance from anon, authenticated;
revoke all on public.tapauth_reservations from anon, authenticated;
revoke all on public.tapauth_public_activity from anon, authenticated;
grant select on public.tapauth_public_activity to anon, authenticated;
drop policy if exists "Public activity is readable" on public.tapauth_public_activity;
create policy "Public activity is readable" on public.tapauth_public_activity
for select to anon, authenticated using (true);
create index if not exists tapauth_public_activity_latest
on public.tapauth_public_activity(date_logged desc);
